### ISSUE TITLE
토비의 스프링 3.1을 읽고나서

### ISSUE THREAD

**Issue by ssibongee** [Today-I-Learn/dev-reading-record#8]
2021-04-12 ~ 2021-05-31 약 두달간 진행한 "토비의 스프링 3.1" 읽기를 끝마치고 이를 통해 얻은 가치와 고민할 거리들 회고를 기록합니다!

* [Jiho Shin 님의 회고](https://today-i-learn.github.io/jhhj424-toby-spring-3.1.html)
* [Sangwon Jeong 님의 회고](https://today-i-learn.github.io/vincentj2-toby-spring-3.1.html)

**Comment by jhhj424** [comment]
모두 두달간 고생 많으셨습니다~~ 👍 

회고 글 작성중이고, 조만간 업로드 하겠습니다 :)
